modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/LumberWizard/Scholarly-Arcana/issues"
license="MIT"
[[mods]]
modId="scholarlyarcana"
version="${file.jarVersion}"
displayName="Scholarly Arcana"
authors="Lumber Wizard"
description='''
This is a magic mod, it adds stuff

In the future it will even have a good description
'''
[[dependencies.scholarlyarcana]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.scholarlyarcana]]
    modId="jei"
    mandatory=false
    versionRange="[8.0.0.12,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.scholarlyarcana]]
    modId="curios"
    mandatory=false
    versionRange="[1.17.1-5.0.0.1,)"
    ordering="AFTER"
    side="BOTH"